# This is a basic workflow to help you get started with Actions

name: Shared actions example

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  
  checkout-repo:
 
    runs-on: ubuntu-latest

   
    steps:
     
      - uses: actions/checkout@v4

      -  run: ls

 